### ISSUE TITLE
 templates:load-source and loadsource.js

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/templating#4]
I have a question about ` templates:load-source` according to [this snippet](https://github.com/eXist-db/shared-resources/blob/ea2e9777870616eb64213401856cf8b1cccc6d31/resources/scripts/loadsource.js#L4) the function relies on importing `loadsource.js` which is only available from `shared-resources` 

@wolfgangmm have you adjust the code to remove that dependency? Is the feature no longer supported, or can we publish loadsource.js differently

**Comment by wolfgangmm** [comment]
I plan to remove this and drop the feature. Not yet done with my updates ;-)

**Comment by wolfgangmm** [comment]
templates:load-source has been removed.
