### ISSUE TITLE
License and Copyright

### ISSUE THREAD

**Issue by adamretter** [eXist-db/templating#5]
Nice to see this :-)

But... I would like to understand how the license and copyright were chosen.

As far as I can tell the code came from https://github.com/eXist-db/shared-resources and lists several contributors over time. The previous license is only stated as ["GNU-LGPL"](https://github.com/eXist-db/shared-resources/blob/master/repo.xml#L7). The shared resources-code though I think came from the https://github.com/eXist-db/exist code-base originally, which would have been LGPL 2.1.

The new license however appears to be LGPL 3.0. Without an existing CLA in-place or consulting all previous authors, I don't think we can change the license.

Likewise, the new Copyright appears to be `Copyright (c) 2021 eXist-db Project <wolfgang@exist-db.org> (http://exist-db.org)`. Previously there appears not to have been a copyright statement. As there have been several contributors I would have expected it to remain neutral like in the eXist-db project, i.e., `Copyright (C) 2001 The eXist-db Authors`.

Comments?

**Comment by wolfgangmm** [comment]
I think this was all filled in by eXist's yeoman generator (a great tool btw.) when creating the project and I'm not done with correcting yet.
