### ISSUE TITLE
Should the breaking changes in v1.0.3 be reverted?

### ISSUE THREAD

**Issue by joewiz** [eXist-db/templating#8]
v1.0.3, which is the current version in the master branch but has not been published, contains a change that I think could be considered a breaking change: a change in the name of the parameters for the `lib:parse-params()` function. The commit that made this change is https://github.com/eXist-db/templating/commit/9eef08b2241fddc8dac824a6f1866353dca0dfbb. Anyone using `lib:parse-params()` from v1.0.1 or v1.0.2 would need to adjust their code to work with this commit. 

To reflect this breaking nature of the change, I'd propose that the version be incremented to v2.0.0 and released with this change. Affected apps that aren't ready for the change should set a semver-max to "1.99.99" in their expath-pkg.xml's dependency on this app.

**Comment by joewiz** [comment]
Alternatively, packages could declare `semver="1.0.2"`.

**Comment by joewiz** [comment]
Or should we revert the breaking changes for now so that development of 1.x can continue, and then reinstate the breaking commits when there is a compelling need?

- https://github.com/eXist-db/templating/commit/9eef08b2241fddc8dac824a6f1866353dca0dfbb
- https://github.com/eXist-db/templating/commit/15d8cba13bdd83e4bf5e29c5b09999d3dbdb50c3

Because as it is, development is stuck in place...

Unless I hear otherwise, I think I'd best revert the commits soon so we can publish a new release with the other improvements that have been merged since then.

**Comment by joewiz** [comment]
In today's Community Call @line-o supported the approach described above - of reverting the breaking change from the unreleased 1.0.3 version and releasing a new version with the improvements that have come in. 

@wolfgangmm Please let me know if you need these changes to stay in the 1.x. If not, then I'll probably go ahead and perform the changes and prepare a new release later this week.

**Comment by wolfgangmm** [comment]
@joewiz I agree, please revert the breaking change.

**Comment by joewiz** [comment]
@wolfgangmm Ok, I've prepared a PR reverting the commit. Once it's merged, I'll prepare a new release as 1.0.4 - just in case anyone used 1.0.3.
